### ISSUE TITLE
Templating Engine Support (as Middleware, ideally)

### ISSUE THREAD

**Issue by reem** [iron/iron#125]
mustache is probably the only thing worth supporting right now

**Comment by sunng87** [comment]
Hi, I have talked with @reem in IRC but also want to update here. I have been working on a [handlebars template engine for rust](https://github.com/sunng87/handlebars-rust) and I'm going to create an [iron middleware](https://github.com/sunng87/handlebars-iron) for integration.

By far, the handlebars-rust project is almost finished and should support most of handlebars features, helper customization and template inheritance. I'm now working on the middleware. Since it's still difficult to compile iron against rust nightly, I may still need several days for it.

As discussed with @reem, we will create a new `Template` struct contains template name and data you want to render. `Template` will implement `Modifier` for `Response`, so users can call `response.set(template)`. The information will be stored in extensions and processed by middleware. I'm also going to keep it easy to test. So users can test their handlers by retrieving data from extensions (in test function).

**Comment by sunng87** [comment]
To answer some questions above, handlebars is a widely used template syntax created by Yokuda Hatz (yes, it's who made cargo also) originally in javascript. In handlebars-rust, there is a tricky point that you have to make the data implements `ToJson` so we can render it. Because in handlebars, there's if/else, each and some other custom flow controls, data are not only for rendering, but also to control rendering. So I can't just use a "Show" trait or String/&str type for it. Lucky enough, most common data structure implements `ToJson`, so we can use it without (too much) pain.

**Comment by reem** [comment]
Just a note, but its Yehuda Katz, aka wycats. :)

**Comment by sunng87** [comment]
Oh, sorry for wycats.

**Comment by sunng87** [comment]
The middleware [handlebars-iron](https://github.com/sunng87/handlebars-iron) is done and available from crates.io

**Comment by untitaker** [comment]
I think this can be closed since handlebars-iron seems to work fairly well.
