### ISSUE TITLE
Compile Common

### ISSUE THREAD

**Issue by reem** [iron/iron#143]
- [x] Router
- [x] Mount
- [x] Persistent
- [ ] Static File
- [ ] Parsers (unlikely to be fixed, should be obsoleted by decode when I get something working)
- [ ] Logger
- [ ] Cookie
- [ ] Session 

Not Common:
- [ ] Iron-Cors
- [ ] Iron-Test

**Comment by ProtectedMode** [comment]
You should uncheck "Logger" and "Static File" since these don't compile. Maybe you should also create a note in the readme about the current state of middleware, since the current state is a bit deceiving in my opinion.

I also want to emphasize the need for these middleware crates to compile, since a framework is basically useless without them for a bit more advanced projects...

**Comment by reem** [comment]
@ProtectedMode I agree completely. Recently it's been a challenge to keep just Iron itself compiling, but now that things are calming down a bit I think we get back to stability (and getting everything compiling).

**Comment by reem** [comment]
This issue is pointless and outdated, obviously we want things to compile, but there is no need to track everything here.

**Comment by brycefisher** [comment]
:+1:
