### ISSUE TITLE
Swagger 2.0 support

### ISSUE THREAD

**Issue by schickling** [iron/iron#213]
I'm a huge fan of the Swagger API documentation project (http://swagger.io). For many frameworks in many different languages support for Swagger is already implemented and yields a big advantage.

I think it would be awesome to provide Swagger support for nickel as well. What do you guys think is the best approach? Perhaps as a standalone crate which can be somehow mounted and fed with the request struct?

Looking forward to your thoughts on Swagger.

**Comment by s-panferov** [comment]
I have been implementing Swagger 2.0 support in [Rustless](https://github.com/rustless/rustless). It's quite easy in Rustless, because it has a knowledge about request params schema. 

After that, using my experience, I'll try to implement it for Iron. I think it's not a big deal in a simple case, but it requires some knowledge about request parameters and responses:

1. We can leave them blank (it's not very informative).
2. We can allow to specify JSON-schema files.
3. We can provide some DSL to describe input parameters and responses.

**Comment by schickling** [comment]
I think the third option (DSL) would be the best fit. Could this be implemented as a middleware or does it have to be in the core?

**Comment by sunng87** [comment]
I believe this is too high-level to be in the core. From its clojure/ring implementation and [application](https://github.com/metosin/compojure-api), I think it will be implemented as a standalone library/framework, maybe mount-able to ring and has its own default routers.

**Comment by reem** [comment]
From the discussion it looks like this can be done out of core, so I'm closing.

Feel free to rekindle discussion elsewhere or try to convince me that this needs to go in iron proper and I should reopen.

**Comment by s-panferov** [comment]
> After that, using my experience, I'll try to implement it for Iron. I think it's not a big deal in a simple case,  > but it requires some knowledge about request parameters and responses:
> 
> 1. We can leave them blank (it's not very informative).
> 2. We can allow to specify JSON-schema files.
> 3. We can provide some DSL to describe input parameters and responses.

I just want to add to my items:

1. This is pretty useless.
2. Now I have been working on JSON Schema library for Rust. After I'll finish the library, this scenario can be implemented for [iron/router](https://github.com/iron/router).
3. This is already covered by [rustless](https://github.com/rustless/rustless) and I see unrealistic to make the same in some *simple* Iron middleware.
