### ISSUE TITLE
Allow regexp-based routing and param capture

### ISSUE THREAD

**Issue by kerinin** [iron/iron#240]
A handy feature of Martini is the ability to use regexps and named capture groups to route requests (https://github.com/go-martini/martini#routing).  

This can be helpful for constraining the format of parameters, or for parsing more complex routes than simple globs allow.

Looks like you're using `route-recognizer` for globbing, so I guess this would require re-writing the path matcher.

**Comment by reem** [comment]
The current approach is much faster and has a simpler implementation (from Iron's perspective), so I doubt this change will be made. If you have any killer reasons or examples of why regex based routing is needed over our current glob and param matching, I might be convinced, but otherwise closing as wontfix.
