### ISSUE TITLE
Files upload

### ISSUE THREAD

**Issue by s-panferov** [iron/iron#263]
Hello @reem, have you already thought about support of file uploads with `multipart/form-data`? Maybe you have some ideas how it can be implemented the best way.

It looks like @cybergeek94 already made [multipart](https://github.com/cybergeek94/multipart) library for Hyper, but he has some [issues with Iron integration](https://github.com/cybergeek94/multipart/issues/1). What do you think about it?

**Comment by cybergeek94** [comment]
I haven't been maintaining multipart lately due to lack of interest but I definitely wouldn't mind it becoming a component of Iron.

The main issue is that Iron provides the request body to its middleware as `Vec<u8>` which is kind of a bad idea if you want to support large request bodies, such as with file uploads. I shared some ideas in a Reddit discussion a while back but I don't know if anything came of that.

**Comment by reem** [comment]
It's possible that `Request` could be changed to allow streaming of the input data. I've thought about it and the issues that come up with direct `Response` streaming aren't really an issue for `Request`, since there is only one state (i.e. no "status line written", "headers written", "nothing written" etc.). 

The major issue I anticipate is that this makes testing a bit trickier, but from my memory of the internals of Hyper I think it's actually pretty easy to mock an `HttpWriter` with whatever data you want. This also has the side-effect of making `Request` no longer `'static` or `Send` (since `HttpWriter` is given to us by Hyper with a lifetime), which can be a pain.

**Comment by reem** [comment]
I can take a crack at making this change tomorrow, but it's not too complex a change and probably interesting if either of you wants to give it a try first.

**Comment by reem** [comment]
We now allow streaming the request body, so Iron should now be able to support this use case well.
