### ISSUE TITLE
Build on only stable rust

### ISSUE THREAD

**Issue by reem** [iron/iron#318]
Needed unstable APIs:

- [x] `std::error::Error`
- [x] `std::fs::File::path`

cc #317 (in contrast this bug is just for this repo)

**Comment by aturon** [comment]
Note that `File::path` is not likely to be stabilized soon -- it will probably be deprecated instead. Its primary use was for providing more informative error messages internally, but as part of the reform we've been stripping out these extra layers of functionality (and making the core IO types be thin wrappers around descriptors).

**Comment by reem** [comment]
Hmm, that's inconvenient since it means we won't be able to automatically set the content type when a File is passed to set the body of a response. That said, it's not necessarily blocking. Could we grow an API based on `readlink` in the future, or is that unlikely to happen?

**Comment by Parakleta** [comment]
This patch (a533de8) seems a little clumsy, since it leaves the comment on [#L93](https://github.com/iron/iron/blob/a255647264d198016e753019be2dbe1d120a6d7e/src/modifiers.rs#L93) which is no longer correct and didn't duplicate the mime setting behaviour into the `PathBuf` variant on [#L128](https://github.com/iron/iron/blob/a255647264d198016e753019be2dbe1d120a6d7e/src/modifiers.rs#L128).

Is it possible to chain either `&Path` or `PathBuf` through the other to save duplicated code?  Alternatively since `PathBuf` implements `Deref` into `Path` can one or the other variant just be discarded (I'm still a bit fuzzy on how `Deref` works)?
