### ISSUE TITLE
HttpResult -> Result

### ISSUE THREAD

**Issue by Yamakaky** [iron/iron#372]
Did you consider renaming HttpResult to Result ? See http://doc.rust-lang.org/std/io/type.Result.html.

**Comment by reem** [comment]
`HttpResult` is actually a reexport of `hyper::Result`, I've made it a longer name to make it clear it is not the Result type used ubiquitously in Iron, that is `IronResult`. `IronResult` is not called `Result` since it is in the iron `prelude` module, and putting a `Result` symbol in there would not work well.

I use the renaming-Result idiom in many crates, but it doesn't fit well in this case.

**Comment by Yamakaky** [comment]
Ok
