### ISSUE TITLE
Benchmark

### ISSUE THREAD

**Issue by yesmin** [iron/iron#441]
In i7-4980HQ all 8 threads.

[http://ark.intel.com/products/83503/Intel-Core-i7-4980HQ-Processor-6M-Cache-up-to-4_00-GHz](http://ark.intel.com/products/83503/Intel-Core-i7-4980HQ-Processor-6M-Cache-up-to-4_00-GHz)

**Comment by untitaker** [comment]
...what?

**Comment by mtib** [comment]
...what?

**Comment by yesmin** [comment]
The processor intel i7-4980HQ with 8 threads, the performance test is invalid.

Page [https://github.com/iron/iron/wiki/How-to-Benchmark-hello.rs-Example](Benchmark)

Sorry for bad English.

**Comment by untitaker** [comment]
How is the performance test invalid because of this processor?

**Comment by untitaker** [comment]
Ah, now I understand. From the page:

>Total Number of Threads: 12

This refers to the amount of POSIX threads the Iron server spawns.

You are claiming this is outdated/wrong/invalid because the Intel page claims that this Intel CPU has only 8 threads.

This is not relevant though: You can spawn as many POSIX threads as you like, independent of the CPU.
