### ISSUE TITLE
Cannot borrow *req as a mutable

### ISSUE THREAD

**Issue by alanhoff** [iron/iron#460]
Hello folks,

I'm trying to use a middleware that I wrote and the `params` crate, but if I try to use `req` more than once the compiler complains:

```
cargo run
   Compiling rustbr v0.1.0 (file:///Users/alanhoff/Projects/rustbr)
src/resources/user.rs:16:23: 16:26 error: cannot borrow `*req` as mutable because `req.extensions` is also borrowed as immutable [E0502]
src/resources/user.rs:16     let mut payload = req.get_ref::<Params>();
                                               ^~~
src/resources/user.rs:15:26: 15:40 note: immutable borrow occurs here
src/resources/user.rs:15     let mut connection = req.extensions.get::<db::Database>().unwrap();
                                                  ^~~~~~~~~~~~~~
src/resources/user.rs:21:1: 21:2 note: immutable borrow ends here
src/resources/user.rs:21 }
                         ^
src/resources/user.rs:16:23: 16:26 help: run `rustc --explain E0502` to see a detailed explanation
error: aborting due to previous error
error: Could not compile `rustbr`.
```

This is what my handle looks like:

```rust
fn create (req: &mut Request) -> IronResult<Response> {
    let mut connection = req.extensions.get::<db::Database>().unwrap();
    let mut payload = req.get_ref::<Params>();

    println!("{:?}", payload);

    Ok(Response::with((status::Ok)))
}
```

All that my `Database` middleware does is to put a `r2d2` connection pool into each request. This looks like I'm having problems to understand the concept of the language so I would appreciate if someone have the patience to help me sort this out.

Thanks!

**Comment by SkylerLipthay** [comment]
Hi!

[`req.extensions.get`](http://ironframework.io/doc/iron/typemap/struct.TypeMap.html#method.get) captures `&self`, so `req` itself is immutably borrowed for the rest of the scope (in this case, the rest of the function). [`req.get_ref`](http://ironframework.io/doc/iron/prelude/trait.Pluggable.html#method.get_ref) tries to capture `&mut self`, but `req` cannot be mutably borrowed while any other borrows (mutable *or* mutable) are active.

`Pluggable`, through which `params::Map` is accessed, requires `&mut self`. For Iron's sake, this is nice because it allows plugins to "mutate" the request (in this case, reading from the request body stream to extract parameters).

Anyway, a simple fix would be to reverse the order of the `let connection` and `let payload` lines; `payload` itself doesn't hold on to a reference of `req`, but `connection` does.

Or, you may be interested in dropping usage of the `extensions` `TypeMap` altogether and using a `Plugin` to access the database. [Here's one example](https://github.com/superlogical/rustwebapp/blob/master/src/main.rs#L132) that uses Iron's `persistent` crate, which uses `Arc` internally to help you avoid these borrow/lifetime ergonomics issues.

I'm not 100% sure if it's the intentional semantics of Iron, but `req.extensions` seems to be used for storing *pre-calculated data* specifically for communication between middleware (such as with Iron's `router` middleware). Plugins are suited for *lazy evaluation*, and can also provide caching for the resultant data. `params` is a plugin because not all requests need to access request parameters, so they should only be deserialized when requested. In many ways, I think it's semantically correct for database access to be through plugins.

Sorry, I think I'm babbling. :smile: Hopefully this shed some light on your situation.

**Comment by alanhoff** [comment]
That was supper informative! Many thanks :-)

**Comment by beanieboi** [comment]
@SkylerLipthay I stumbled across the same issue and your comment was super helpful! Thank you!
