### ISSUE TITLE
removing pub mod status was a breaking change

### ISSUE THREAD

**Issue by kcking** [iron/iron#589]
https://github.com/iron/iron/commit/758a7400a07cceb6c81b35019069314bd37dc75e removed the exported `status` module from the crate root, breaking https://github.com/dbrgn/iron-cors-rs

Would it be possible to bump the version to `0.7` so that dependent crates can reliably work off of the new public API?

**Comment by alxbl** [comment]
FYI this also breaks the existing `router` module for iron, which still uses `status` everywhere.

**Comment by phlmn** [comment]
We will have to introduce a few breaking changes with 0.7 since hyper did change quite a lot of things. https://github.com/iron/iron/commit/758a7400a07cceb6c81b35019069314bd37dc75e was just some cleanup, as you can see in https://github.com/iron/iron/commit/64f992b99385daeb89c60b2b1619da3d85cdd0c0 you would have to update the usage of `status` anyway.

Since 0.7 is work in progress there might follow other breaking changes. I don't think bumping the version before releasing would make any difference, but the 0.7 release should not be so far down the road. 🙂
